-- ============================================================================
-- SmartShip — รายการคอลัมน์ตารางขนส่ง (นิยามเต็มอยู่ที่ Supabase)
-- มี 2 ตารางที่โครงสร้างเหมือนกันทุกคอลัมน์ แยกตามแพลตฟอร์ม:
--   1) public.jt_shipments      — ขนส่ง J&T (dashboard: /admin/jt-dashboard)
--   2) public.tiktok_shipments  — TikTok Shop (dashboard: /admin/tiktok-dashboard)
-- ทั้งคู่ใช้ awb_number เป็น PRIMARY KEY และนำเข้าผ่าน n8n webhook (upsert)
-- ============================================================================

-- ==================== ตารางที่ 1: public.jt_shipments ====================
-- อ้างอิง: app/api/admin/jt-shipments/dashboard/route.ts | parse เงิน: src/lib/jtMoneyText.ts
-- upload ผ่าน n8n: NEXT_PUBLIC_N8N_UPLOAD_WEBHOOK_URL
awb_number text NOT NULL PRIMARY KEY,
    booking_date text,
    sender_name text,
    sender_phone text,
    receiver_name text,
    receiver_phone text,
    
    shipping_fee text,
    remote_area_fee text,
    cod_amount text,
    total_shipping_fee text,
    cod_payment_method text,
    cod_status text,
    cod_payment_time text,
    
    prev_branch_code text,
    prev_branch_name text,
    issue_status text,
    return_type text,
    delivery_method text,
    collected_time text,
    
    shop_name text,
    avg_weight text,
    volumetric_weight text,
    parcel_volume text,
    total_height text,
    width text,
    length text,
    gateway_vol_weight text,
    gateway_weight text,
    gateway_height text,
    gateway_width text,
    gateway_length text,
    total_vol_weight text,
    
    dest_zipcode text,
    order_source text,
    sort_code_all text,
    sort_code_part4 text,
    signer_name text,
    customer_branch text,
    receiver_address text,
    dest_subdistrict text,
    dest_district text,
    dest_province text,
    dest_code text,
    receiver_home_phone text,
    
    return_fee text,
    insurance_fee text,
    sign_branch_code text,
    sign_branch_name text,
    signed_time text,
    delivery_staff_id text,
    delivery_staff_name text,
    dispatch_time text,
    
    order_weight text,
    center_weight text,
    received_weight text,
    billed_weight text,
    total_received_vol_weight text,
    received_height text,
    received_width text,
    received_length text,
    product_name text,
    
    issue_registered_time text,
    exception_reason text,
    return_branch_name text,
    return_branch_code text,
    discount_amount text,
    amount_before_discount text,
    gateway_received_weight text,
    gateway_sort_code text,
    is_cod_collection text,
    other_fees text,
    
    latest_scan_type text,
    latest_scan_branch text,
    latest_scan_time text,
    
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()

-- ==================== ตารางที่ 2: public.tiktok_shipments ====================
-- TikTok Shop — โครงสร้างคอลัมน์เดียวกับ jt_shipments ทุกคอลัมน์
-- อ้างอิง: app/api/admin/tiktok-shipments/route.ts | upload ผ่าน n8n: TIKTOK_N8N_UPLOAD_WEBHOOK_URL
-- SQL migration: database/db/migrations/20260521_tiktok_shipments.sql
awb_number text NOT NULL PRIMARY KEY,
    booking_date text,
    sender_name text,
    sender_phone text,
    receiver_name text,
    receiver_phone text,

    shipping_fee text,
    remote_area_fee text,
    cod_amount text,
    total_shipping_fee text,
    cod_payment_method text,
    cod_status text,
    cod_payment_time text,

    prev_branch_code text,
    prev_branch_name text,
    issue_status text,
    return_type text,
    delivery_method text,
    collected_time text,

    shop_name text,
    avg_weight text,
    volumetric_weight text,
    parcel_volume text,
    total_height text,
    width text,
    length text,
    gateway_vol_weight text,
    gateway_weight text,
    gateway_height text,
    gateway_width text,
    gateway_length text,
    total_vol_weight text,

    dest_zipcode text,
    order_source text,
    sort_code_all text,
    sort_code_part4 text,
    signer_name text,
    customer_branch text,
    receiver_address text,
    dest_subdistrict text,
    dest_district text,
    dest_province text,
    dest_code text,
    receiver_home_phone text,

    return_fee text,
    insurance_fee text,
    sign_branch_code text,
    sign_branch_name text,
    signed_time text,
    delivery_staff_id text,
    delivery_staff_name text,
    dispatch_time text,

    order_weight text,
    center_weight text,
    received_weight text,
    billed_weight text,
    total_received_vol_weight text,
    received_height text,
    received_width text,
    received_length text,
    product_name text,

    issue_registered_time text,
    exception_reason text,
    return_branch_name text,
    return_branch_code text,
    discount_amount text,
    amount_before_discount text,
    gateway_received_weight text,
    gateway_sort_code text,
    is_cod_collection text,
    other_fees text,

    latest_scan_type text,
    latest_scan_branch text,
    latest_scan_time text,

    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()