/**
 * ข้อมูลจำลองสำหรับทดสอบ UI — ชนิดแถวดู `jtDashboardTypes.ts` (จอย schema.sql)
 */

import type { JtDashboardMetrics, JtDashboardShipmentRow } from './jtDashboardTypes';

export type { JtDashboardMetrics, JtDashboardShipmentRow } from './jtDashboardTypes';
export const MOCK_METRICS: JtDashboardMetrics = {
    totalParcels: 1533,
    closedCount: 1400,
    sumCod: 7812,
    avgShippingFee: 52.35,
    returnCount: 24,
    jmsCount: 612,
    // Business KPIs (P6) — ตัวเลขจำลองให้สอดคล้องกับ RPC `jt_dashboard_fixed_totals`
    sumTotalFeeJms: 11128.5,
    sumTotalShippingFee: 15000.0,
    codPaidCount: 626,
    codPaidAmount: 138700.68,
    codPendingCount: 747,
    codPendingAmount: 190266.55,
    codNoCollectionCount: 992,
    exceptionCount: 4,
    stagnantCount: 2,
    stagnantCases: [
        {
            awb_number: '8200011220001',
            booking_date: '2026-05-10',
            sender_name: 'ร้านตัวอย่าง A',
            sender_phone: '0812345678',
            gateway_width: '20',
            gateway_height: '15',
            gateway_length: '30',
            gateway_weight: '1.5',
            gateway_vol_weight: '1.8',
            latest_scan_time: '2026-05-14 10:00:00',
        },
        {
            awb_number: '8200011220002',
            booking_date: '2026-05-08',
            sender_name: 'ร้านตัวอย่าง B',
            sender_phone: '0898765432',
            gateway_width: '-',
            gateway_height: '-',
            gateway_length: '-',
            gateway_weight: '0.8',
            gateway_vol_weight: '-',
            latest_scan_time: '-',
        },
    ],
    stagnantHiddenCases: [
        {
            awb_number: '8200011220003',
            reason: 'ตรวจสอบแล้ว — ปกติ',
            acknowledged_at: '2026-05-20 09:30:00',
            acknowledged_by: 'admin',
        },
    ],
    topExceptionReasons: [
        { reason: 'ผู้รับปฏิเสธการชำระเงินหรือปฏิเสธการรับพัสดุ', count: 1 },
        { reason: 'พัสดุคัดแยกผิดร้านสาขานำจ่าย', count: 3 },
    ],
    topExceptionCases: [
        {
            awb_number: '8200011223344',
            sender_name: 'ร้านตัวอย่าง A',
            receiver_name: 'คุณสมชาย ใจดี',
            receiver_phone: '0812345678',
            exception_reason: 'ผู้รับปฏิเสธการชำระเงินหรือปฏิเสธการรับพัสดุ',
            issue_registered_time: '2026-04-30 22:45',
        },
        {
            awb_number: '8200011223345',
            sender_name: 'ร้านตัวอย่าง B',
            receiver_name: 'คุณหนูแดง',
            receiver_phone: '0898765432',
            exception_reason: 'พัสดุคัดแยกผิดร้านสาขานำจ่าย',
            issue_registered_time: '2026-04-30 18:05',
        },
    ],
    topReturnTypeCases: [
        {
            awb_number: '8200011223344',
            sender_name: 'ร้านตัวอย่าง A',
            receiver_name: 'คุณสมชาย ใจดี',
            receiver_phone: '0812345678',
            exception_reason: 'ผู้รับปฏิเสธการชำระเงินหรือปฏิเสธการรับพัสดุ',
            return_branch_name: 'ศูนย์คัดแยกบางนา',
            issue_registered_time: '2026-04-30 22:45',
        },
        {
            awb_number: '8200011223345',
            sender_name: 'ร้านตัวอย่าง B',
            receiver_name: 'คุณหนูแดง',
            receiver_phone: '0898765432',
            exception_reason: 'พัสดุคัดแยกผิดร้านสาขานำจ่าย',
            return_branch_name: 'ศูนย์คัดแยกลาดกระบัง',
            issue_registered_time: '2026-04-30 18:05',
        },
    ],
    returnHiddenCases: [
        {
            awb_number: '8200011229001',
            reason: 'เคลมแล้ว อนุมัติแล้ว',
            acknowledged_at: '2026-05-20 14:10:00',
            acknowledged_by: 'admin',
        },
    ],
    codCollectionRate: 45.59,
};

export const MOCK_RECENT_ROWS: JtDashboardShipmentRow[] = [
    {
        awb_number: 'JT88665544123001',
        booking_date: '2026-05-01T08:30:00.000Z',
        sender_name: 'บริษัท A',
        receiver_name: 'คุณสมชาย ใจดี',
        receiver_phone: '0812345678',
        shipping_fee: '45',
        cod_amount: '1200',
        latest_scan_type: 'สำเร็จ — ลงนามรับ',
        return_type: null,
        exception_reason: null,
        return_branch_name: null,
        issue_registered_time: null,
    },
    {
        awb_number: 'JT88665544122998',
        booking_date: '2026-05-01T07:15:00.000Z',
        sender_name: 'ร้าน BabyMeal',
        receiver_name: 'ร้าน BabyMeal สาขาเซ็นทรัล',
        receiver_phone: '0898765432',
        shipping_fee: '55',
        cod_amount: '0',
        latest_scan_type: 'ระหว่างจัดส่ง',
        return_type: null,
        exception_reason: null,
        return_branch_name: null,
        issue_registered_time: null,
    },
    {
        awb_number: 'JT88665544122955',
        booking_date: '2026-04-30T22:40:00.000Z',
        sender_name: 'ร้านตัวอย่าง B',
        receiver_name: 'คุณหนูแดง',
        receiver_phone: '0651112233',
        shipping_fee: '38',
        cod_amount: '3500',
        latest_scan_type: 'ตีกลับ — ผู้รับไม่อยู่',
        return_type: 'ผู้รับไม่อยู่',
        exception_reason: 'ผู้รับไม่อยู่',
        return_branch_name: 'ศูนย์คัดแยกบางนา',
        issue_registered_time: '2026-04-30 22:45',
    },
    {
        awb_number: 'JT88665544122912',
        booking_date: '2026-04-30T18:00:00.000Z',
        sender_name: 'หจก. ขนส่งเร็ว',
        receiver_name: 'หจก. ขนส่งเร็ว',
        receiver_phone: '024567890',
        shipping_fee: '120',
        cod_amount: '890',
        latest_scan_type: 'Return to sender',
        return_type: 'Return to sender',
        exception_reason: 'ติดต่อผู้รับไม่ได้',
        return_branch_name: 'ศูนย์คัดแยกลาดกระบัง',
        issue_registered_time: '2026-04-30 18:05',
    },
    {
        awb_number: 'JT88665544122888',
        booking_date: '2026-04-30T12:00:00.000Z',
        sender_name: 'บริษัท C',
        receiver_name: 'คุณแอน — รามอินทรา',
        receiver_phone: '0923344556',
        shipping_fee: '42.5',
        cod_amount: '0',
        latest_scan_type: 'สำเร็จ',
        return_type: null,
        exception_reason: null,
        return_branch_name: null,
        issue_registered_time: null,
    },
];
